CREATE PROC dbo.FI_SP_ExisteBeneficiarioPorCpf
    @IDCLIENTE BIGINT,
    @CPF CHAR(11),
    @IDIGNORAR BIGINT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 1 ID
      FROM dbo.BENEFICIARIOS
     WHERE IDCLIENTE = @IDCLIENTE
       AND CPF = @CPF
       AND (@IDIGNORAR IS NULL OR ID <> @IDIGNORAR);
END
GO