CREATE PROC dbo.FI_SP_IncBeneficiario
    @CPF CHAR(11),
    @NOME VARCHAR(50),
    @IDCLIENTE BIGINT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO dbo.BENEFICIARIOS(CPF,NOME,IDCLIENTE)
    VALUES(@CPF,@NOME,@IDCLIENTE);

    SELECT SCOPE_IDENTITY() AS ID;
END
GO