CREATE PROC dbo.FI_SP_PesqBeneficiario
    @IDCLIENTE BIGINT,
    @CPF CHAR(11) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID, CPF, NOME, IDCLIENTE
      FROM dbo.BENEFICIARIOS
     WHERE IDCLIENTE = @IDCLIENTE
       AND (@CPF IS NULL OR CPF = @CPF)
     ORDER BY NOME;
END
GO